"""add description to attached_files

Revision ID: 013d82a2ea7f
Revises: 0c236caa479f
Create Date: 2026-08-03 14:13:49.373028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '013d82a2ea7f'
down_revision: Union[str, Sequence[str], None] = '0c236caa479f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attached_files', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attached_files', 'description')
    # ### end Alembic commands ###
