"""add condition column to patients

Revision ID: 5ee43a5fedef
Revises: b8fd21c76ae8
Create Date: 2026-08-01 13:26:53.284087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ee43a5fedef'
down_revision: Union[str, Sequence[str], None] = 'b8fd21c76ae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('condition', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'condition')
    # ### end Alembic commands ###
