"""add start_date and duration to current_medications

Revision ID: 84e84d80ffc7
Revises: 9faacb50b7c9
Create Date: 2026-08-05 11:43:52.695287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84e84d80ffc7'
down_revision: Union[str, Sequence[str], None] = '9faacb50b7c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('current_medications', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('current_medications', sa.Column('duration', sa.String(length=50), nullable=True))
    op.add_column('prescriptions', sa.Column('start_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prescriptions', 'start_date')
    op.drop_column('current_medications', 'duration')
    op.drop_column('current_medications', 'start_date')
    # ### end Alembic commands ###
