"""add medicine_name to current_medications

Revision ID: 9faacb50b7c9
Revises: 013d82a2ea7f
Create Date: 2026-08-03 14:50:16.900578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9faacb50b7c9'
down_revision: Union[str, Sequence[str], None] = '013d82a2ea7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('current_medications', sa.Column('medicine_name', sa.String(length=255), nullable=False))
    op.alter_column('current_medications', 'medical_act_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('current_medications', 'medical_act_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('current_medications', 'medicine_name')
    # ### end Alembic commands ###
