"""add password_hash to users

Revision ID: b35af9dd2799
Revises: aac172c0eb3f
Create Date: 2026-07-26 16:02:28.690113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b35af9dd2799'
down_revision: Union[str, Sequence[str], None] = 'aac172c0eb3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('smoking_packs_per_day', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('smoking_quit_date', sa.Date(), nullable=True),
    sa.Column('hookah', sa.Boolean(), nullable=True),
    sa.Column('cigarettes', sa.Boolean(), nullable=True),
    sa.Column('alcohol', sa.Boolean(), nullable=True),
    sa.Column('drug_use', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    op.drop_table('habits')
    # ### end Alembic commands ###
